name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          CI: false  # Prevent treating warnings as errors
          REACT_APP_API_URL: https://dashboard-api-217033309165.us-central1.run.app
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: dashboard-55056.firebaseapp.com
          REACT_APP_FIREBASE_PROJECT_ID: dashboard-55056
          REACT_APP_FIREBASE_STORAGE_BUCKET: dashboard-55056.firebasestorage.app
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          REACT_APP_AUTH_MODE: firebase
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          # Deploy to both sites with Firebase CLI
          firebase deploy --only hosting:dashboard-55056,hosting:app-syntheticteams --token "$FIREBASE_TOKEN" 